context:
    version: 1.0.0
package:
    name: inspire_hand_sdk
    version: ${{version}}
source:
  - url: https://github.com/nmarticorena/inspire_hand_ws/archive/aa8bf9446b30bb450338cbab7b19cf8f6a65a597.zip
    sha256: 57df1d3d846084164819ca90489e6acbd7927aba55e96b339aeb2334674837a0
    target_directory: inspire_hand_ws




build:
  skip:
    - win
    - osx
  number: 8
  script:
      - cd $SRC_DIR/inspire_hand_ws/inspire_hand_sdk
      - pip install . -v

requirements:
  host:
    - python
    - pip
    - cyclonedds ==0.10.2
    - unitree_sdk2py
  run:
    - python
    - cyclonedds ==0.10.2
    - cyclonedds-py
    - numpy
    - pyqt
    - pyqtgraph
    - pymodbus ==3.6.9
    - pyserial
    - unitree_sdk2py
    - colorcet




extra:
  recipe-maintainers:
    - nmarticorena
