package:
  name: unitree_mujoco
  version: "0.1.0"

source:
  - url: https://github.com/unitreerobotics/unitree_mujoco/archive/1a37b051a10be723405b7ed6dc839361af036d88.zip
    sha256: f132ec60900e918503236fdf289417e39d228a36e300605b3a2d93c20b1a2edd
    patches: fix-uint.patch




build:
  skip:
    - win
    - osx
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    # - ${{ stdlib('c') }}
    - sysroot_linux-64 2.28.*
    - cmake
    - ninja
  host:
    - eigen
    - boost
    - yaml-cpp
    - boost
    - spdlog
    - fmt
    - unitree_sdk2
    - libmujoco
