context:
    version: 1.0.1
package:
    name: unitree_sdk2py
    version: ${{version}}
source:
  - git: https://github.com/nmarticorena/unitree_sdk2_python.git
    rev: b6232e53b5ea727d34e1213174614e894523bd75




build:
  skip:
    - win
    - osx
  number: 3
  script:
      - pip install . -v

requirements:
  host:
    - python
    - pip
    - py-opencv
    - numpy
    - cyclonedds ==0.10.2
  run:
    - python
    - cyclonedds ==0.10.2
    - numpy


extra:
  recipe-maintainers:
    - nmarticorena
