context:
    version: 1.0.1
package:
    name: unitree_sdk2py
    version: ${{version}}
source:
  - git: https://github.com/nmarticorena/unitree_sdk2_python.git
    rev: d793c5ce111c8c9eb8ec8a2cbc96b25ca0ca5bc2




build:
  skip:
    - win
    - osx
  number: 5
  script:
      - pip install . -v

requirements:
  host:
    - python
    - pip
    # - py-opencv # we dont need this only for the quadrupeds
    - numpy
    - cyclonedds ==0.10.2
  run:
    - python
    - cyclonedds ==0.10.2
    - numpy


extra:
  recipe-maintainers:
    - nmarticorena
