context:
  name: lingbotmap-vslamlab
  version: "1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: https://github.com/Robbyant/lingbot-map
    rev: 1f765332f3d884925e334aa10a8e88fbf533c234

build:
  number: 1
  skip: win or cuda_compiler == "None" or cuda_compiler_version != "12.9"
  script:
   - python -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
    - cuda-version ==${{ cuda_compiler_version }}
    - pytorch-gpu
    - torchvision
    - nmarticorena:flashinfer-python
    - pillow
    - einops
    - safetensors
    - opencv
    - tqdm
    - scipy
  run:
    - python 
    - pytorch-gpu
    - tqdm
    - scipy
    - huggingface_hub
    - viser
    - trimesh
    - onnxruntime
    - matplotlib
    - requests


about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A feed-forward 3D foundation model for reconstructing scenes from streaming data
  homepage: https://github.com/Robbyant/lingbot-map

extra:
  authors:
    - Lin-Zhuo Chen
  recipe-maintainers:
    - nmarticorena
